version: 2

# Sources can be used in other models
sources: 
  - name: public # Schema name
    database: bikestores
    description: This is the public schema in the Postgres database. # Add description for the docs
    tables:
       - name: staffs
         description: One record per order. Includes cancelled and deleted orders.
   
         # let dbt snapshot the freshness of the data in the source tables. This is useful for understanding
         # if your data pipelines are in a healthy state, and is a critical component of defining SLAs for the
         # warehouse.

         freshness:
           warn_after: {count: 6, period: hour}
           error_after: {count: 12, period: hour}
         loaded_at_field: _airbyte_emitted_at 
         columns:
           - name: email
             description: The email of all staff
             tests:
               - not_null

       - name: order_items
      

exposures:
  
  - name: weekly_jaffle_metrics
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      Did someone say "exponential growth"?
    
    depends_on:
      - ref('orders')
      - ref('customers')
      - source('public', 'order_items')

      
    owner:
      name: Claire from Data
      email: data@jaffleshop.com



models:
  - name: orders
    description: '{{ doc("table_events") }}' 
    tests:
      - my_not_null:
          column_name: staff_id

    columns:
      - name: first_name 
        description: The first name of the employee
        tests:
          - not_null
          - unique 
          - dbt_utils.not_constant

      - name: last_name
        description: This is the last name of the employee


