db_nds.sql 
contact.sql                        
supplier_status.sql                
artist.sql                         
product_status.sql                 
product_category.sql               
product_type.sql                   
country.sql                        
state.sql                          
city.sql                           
address.sql                        
address_type.sql                   
phone_number.sql                   
phone_number_type.sql              
email_address.sql                  
email_address_type.sql             
currency.sql                       
currency_rate.sql                  
media.sql                          
format.sql                         
package_type.sql                   
package.sql                        
lead.sql                           
store_type.sql                     
division.sql                       
region.sql                         
occupation.sql                     
subscriber_band.sql                
subscriber_class.sql               
household_income.sql               
interest.sql                       
permission.sql                     
customer_status.sql                
customer_type.sql                  
subscription_status.sql            
business_unit.sql                  
communication_category.sql         
language.sql                       
campaign.sql                       
delivery_status_category.sql       
delivery_status.sql                
store.sql                          
supplier.sql                       
product.sql                        
channel.sql                        
communication.sql                                                 
customer.sql                       
communication_subscription.sql                        
campaign_result.sql                
supplier_performance.sql           
subscription_sales.sql             
order_header.sql                   
order_item.sql                     
address_junction.sql               
phone_number_junction.sql          
email_address_junction.sql         
interest_junction.sql              
channel_junction.sql               
