db_dds.sql   
function_fiscal_period.sql 
function_fiscal_week.sql                      
dim_campaign.sql                   
dim_channel.sql                    
dim_communication.sql              
dim_customer.sql                   
dim_date.sql                       
dim_delivery_status.sql            
dim_format.sql                     
dim_lead.sql                       
dim_package.sql                    
dim_product.sql                    
dim_store.sql                      
dim_subscription_status.sql        
dim_supplier.sql                   
dim_week.sql                       
fact_product_sales.sql             
fact_subscription_sales_with_partition.sql
fact_supplier_performance.sql      
fact_communication_subscription.sql
fact_campaign_result.sql           
